# Change these first
owner: ikhwan32 # Your GitHub organization or username, where this repository lives
repo: uptimevf # The name of this repository

sites:
  - name: PenyanyiVF Reborn
    url: https://musicium.nexter32.repl.co
  - name: Penyanyi VF v3
    url: https://discord-musicbot.nexter32.repl.co
  - name: Uptime VF Bot
    url: https://uptime-discord-bot.nexter32.repl.co
  - name: Penyanyi VF V2
    url: https://evobot-1.nexter32.repl.co
  - name: MusicBot UITM
    url: https://MusicBot-UITM.nexter32.repl.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptimevf
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: dark
  faviconSvg: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: VF Uptime
  introTitle: "**VF Uptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Specialized by Ikhwan Hadi
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
